terraform {
  required_providers {
    fastly = {
      source  = "fastly/fastly"
      version = "~> 8.0"
    }
  }
}

data "aws_region" "current" {}

resource "fastly_service_vcl" "this" {
  name           = var.service_name
  comment        = "Website Service"

  default_ttl    = 300
  stale_if_error = true
  stale_if_error_ttl = 300
  activate       = true
  force_destroy  = var.force_destroy
  
  domain {
    name = var.domain_name
  }

  backend {
    address       = var.backend_address
    name          = "s3"
    override_host = var.backend_address
    use_ssl       = false
    weight        = 100
    shield        = "iad-va-us"
    port          = 80
  }
  
  header {
    action        = "set"
    destination   = "http.Access-Control-Allow-Origin"
    ignore_if_set = false
    name          = "CORS"
    source        = "\"*\""
    type          = "cache"
  }
  
  product_enablement {
    brotli_compression = true
  }

  gzip {
    name = "Generated by terraform"
    extensions = ["css","js","html","eot","ico","otf","ttf","json","svg", "md"]
    content_types = ["text/html","application/x-javascript","text/css","application/javascript","text/javascript","application/json","application/vnd.ms-fontobject","application/x-font-opentype","application/x-font-truetype","application/x-font-ttf","application/xml","font/eot","font/opentype","font/otf","image/svg+xml","image/vnd.microsoft.icon","text/plain","text/xml","binary/octet-stream"]
  }
  
}

resource "fastly_tls_subscription" "this" {
  count                 = var.enable_tls ? 1 : 0
  domains               = [var.domain_name]
  certificate_authority = "lets-encrypt"
}

