# ------------------------------------------------------------------------------
# brand.avagolf.com
# ------------------------------------------------------------------------------
# Static Astro site:
#   GitHub Actions builds `dist/` -> syncs to S3 -> Fastly fronts the bucket.
# DNS lives in the avagolf.com zone (managed in the ava.golf infra repo);
# we only manage the brand subdomain record here.

module "brand_avagolf_com_storage" {
  source                = "./modules/aws_s3_website"
  bucket_name           = "brand.avagolf.com"
  enable_access_logging = true
}

resource "fastly_service_vcl" "brand_avagolf_com" {
  name               = "brand.avagolf.com"
  comment            = "Website Service"
  default_ttl        = 300
  stale_if_error     = true
  stale_if_error_ttl = 300
  activate           = true

  domain {
    name = "brand.avagolf.com"
  }

  backend {
    address       = module.brand_avagolf_com_storage.website_endpoint
    name          = "s3"
    override_host = module.brand_avagolf_com_storage.website_endpoint
    use_ssl       = false
    weight        = 100
    shield        = "iad-va-us"
    port          = 80
  }

  request_setting {
    name      = "force-ssl"
    force_ssl = true
  }

  header {
    action        = "set"
    destination   = "http.Access-Control-Allow-Origin"
    ignore_if_set = false
    name          = "CORS"
    source        = "\"*\""
    type          = "cache"
  }

  header {
    action      = "set"
    destination = "http.Strict-Transport-Security"
    name        = "HSTS"
    source      = "\"max-age=31536000; includeSubDomains\""
    type        = "response"
  }

  product_enablement {
    brotli_compression = true
  }

  gzip {
    name          = "Generated by terraform"
    extensions    = ["css", "js", "html", "eot", "ico", "otf", "ttf", "json", "svg", "md"]
    content_types = ["text/html", "application/x-javascript", "text/css", "application/javascript", "text/javascript", "application/json", "application/vnd.ms-fontobject", "application/x-font-opentype", "application/x-font-truetype", "application/x-font-ttf", "application/xml", "font/eot", "font/opentype", "font/otf", "image/svg+xml", "image/vnd.microsoft.icon", "text/plain", "text/xml", "binary/octet-stream"]
  }
}

# The avagolf.com TLS subscription in the ava.golf repo already covers
# *.avagolf.com, so no per-subdomain subscription is needed here.

output "fastly_service_id" {
  value = fastly_service_vcl.brand_avagolf_com.id
}

output "s3_bucket" {
  value = module.brand_avagolf_com_storage.bucket_name
}
